### ISSUE TITLE
cant compile*( 

### ISSUE THREAD

**Issue by victor20010** [nevioo1337/Unmapper#1]
tryed to compile the dll but if i turn off optimization get this error LINK : fatal error C1900:  if dont turn off get this error 1>LINK : fatal error C1047: Файл объекта или библиотеки "B:\dbg\repos\Unmapper-master\lib\Win32\Release\\libMinHook.lib" был создан в другой версии компилятора по сравнению с другими объектами, например, "B:\dbg\repos\Unmapper-master\build\Unmapper\Release\dllmain.obj"; будет выполнено перестроение всех объектов и библиотек с использованием одной и той же версии компилятора
im tryed to compile with Visual Studio 2022 (v143),Visual Studio 2019 (v142) and Visual Studio 2017 (v141) the last one get error  Элемент <LanguageStandard> имеет недопустимое значение "stdcpp20". so i change it to Стандарт ISO C++17 (/std:c++17) but then  i get this error fatal error C1047: Файл объекта или библиотеки "B:\dbg\repos\Unmapper-master\build\Unmapper\Release\dllmain.obj" был создан с более старой версией компилятора, чем другие объекты; выполните заново построение старых объектов и библиотек , sorry for bad english

**Comment by nevioo1337** [comment]
compiling [MinHook](https://github.com/TsudaKageyu/minhook) yourself should resolve all your issues
